### ISSUE TITLE
使用百川模型出现报错

### ISSUE THREAD

**Issue by luxiy123** [xufengduan/MacBehaviour#1]
最初使用作者提供的Llama-2-70b-chat-hf模型运行作者预印文章中的demo，能够成功出结果，

现在我使用的是百川api，在setkey successful的情况下，runExperiment出现报错：
error with code: 400，mesage提示"you must provide a model parameter"。

参考百川官方参数文档，似乎没有缺失必填参数。

尝试调整precheck中的参数，依然无效，但是运行precheck时一直出现以下警告
Warning message:
In value[[3L]](cond) :
  There was an error in token Check: Failed to connect server, but it doesn't affect continued use.
  
  不知道问题到底出在哪里，希望能够得到帮助，谢谢！

**Comment by xufengduan** [comment]
Thanks for your feedback. The bug was fixed. Please update the package (uninstall in R and install it from github).
